### ISSUE TITLE
2022/12 Migration stuck and holding back many packages

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-webengine-feedstock#17]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

i've been trying to push forward with a few migrations (gstreamer and others) but when i got here I found this build to be quite involved.

It seems that new security features are stopping the initial cloning and causing things to fail.

I haven't been able to refactor the feedstock to use archives intead of git.

https://github.com/conda-forge/qt-webengine-feedstock/pull/15#issuecomment-1334607912

This is making installing packages like spyder (cc @conda-forge/spyder ) harder.

Just wanted to create a tracking issue for this.

Best,

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by ccordoba12** [comment]
Thanks @hmaarrfk! Is there something we can do to help? Do you need a hand to compile this package on a specific platform?

**Comment by hmaarrfk** [comment]
hey @ccordoba12 i tagged you since spyder is one of the few packages i know that has a hard dependency on this.

Honestly, I'm somewhat "done" for the week for this package. 


You can try to start off from:
https://github.com/conda-forge/qt-webengine-feedstock/pull/15

OSX and Windows are timing out on CIs.

Linux I got past chromium, but not much further.

Feel free to branch and experiment.
