### ISSUE TITLE
Upload packages

### ISSUE THREAD

**Issue by andfoy** [conda-forge/qt-webengine-feedstock#2]
I have build all the packages for `linux-64`, `osx-64`, `win-64` on my personal channel: https://anaconda.org/andfoy/qt-webengine,
packages for `osx-arm64` are available, although they might need to be rebuilt after https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/225. `linux-aarch64` packages are not available since https://github.com/conda-forge/qt-main-feedstock/issues/5 has not been addressed yet.

@conda-forge/core, I would appreciate your help copying the packages for `qt-webengine` from my personal channel to the conda-forge one since they cannot be built using the CIs.

**Comment by Tobias-Fischer** [comment]
Hi @andfoy, many thanks again for this effort! I'm not part of core but I'd love to see this addressed. I'm assuming that the logs are needed? Also did you have any luck with the aarch packages, or do you need any help?

**Comment by andfoy** [comment]
Since https://github.com/conda-forge/qt-main-feedstock/issues/5 was finally fixed, I'm building the corresponding `aarch64` packages. The logs are the same that were presented on https://github.com/conda-forge/staged-recipes/pull/17233#issuecomment-1016633307

**Comment by andfoy** [comment]
Update: The `aarch64` package is now up on my channel

**Comment by hmaarrfk** [comment]
Do you have the logs by any chance?

If so, if you can follow the guidelines in:
https://github.com/conda-forge/cfep/blob/main/cfep-03.md

ie. upload the logs, and create a unique label for the package for me to copy. then somebody from conda-forge/core (myself included) can copy them along.

**Comment by hmaarrfk** [comment]
I realize that you likely built these more than 2 weeks ago.

**Comment by andfoy** [comment]
Right now I'm fixing some issues with cross-compilation on arm64: https://github.com/conda-forge/qt-webengine-feedstock/pull/1, since I'm building on an M1 Mac directly, I wasn't able to track some of the issues. Once that's done, I'll proceed to recompile everything

**Comment by hmaarrfk** [comment]
Thank you!

I just wanted to point to where our instructions are for these particular requests so that we don't have to repeat the back and forth too much.

I'll see if I can help write a bot to do this over the weekeend.

**Comment by andfoy** [comment]
Thanks a lot @hmaarrfk

**Comment by andfoy** [comment]
Hi @hmaarrfk, thanks for you help uploading the `aarch64` packages for `qt-main`. After that, I compiled all the packages for `qt-webengine` as follows:

| Build variant | Build Log |
|:----------------:|:-------------:|
| `linux-64`     | [Link](https://drive.google.com/file/d/1tbTcWhWXdB3LydMy3SH9R4885n-JJI5-/view?usp=sharing)  |
| `linux-aarch64` | [Link](https://drive.google.com/file/d/11jfNUKYjpkQ7WqkQmqWSMy_5m9AfUbyh/view?usp=sharing) |
| `osx-64` | [Link](https://drive.google.com/file/d/1TFaK6ZiLeVrsYlMv2tPrkwLa73bwq7Lu/view?usp=sharing) |
| `osx-arm64` | [Link](https://drive.google.com/file/d/1Fa-gdotCXhtZBUPxsesyc14QwFdOT74x/view?usp=sharing) |
| `win-64` | [Link](https://drive.google.com/file/d/1YhP4o7pCdYxFxyvW99fzzUXFDTTjR2pt/view?usp=sharing) |

The packages are now up on my channel and all they have the `cf-copy` label:

![image](https://user-images.githubusercontent.com/1878982/157070762-9c6fc6ce-e189-41c8-b2bd-a9fbbbed6872.png)

I would appreciate all your help with this one, please let me know if I can help you somehow.

**Comment by hmaarrfk** [comment]
All uploaded. Thanks.

**Comment by andfoy** [comment]
Thanks a lot for your help @hmaarrfk
